select * from customer

--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue from customer 
group By gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount from customer
where discount_applied = 'Yes' And purchase_amount > (select AVG(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, avg(review_rating) as avg_product_rating from customer 
group by item_purchased
order by avg_product_rating desc

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, avg(purchase_amount),2 avg_revenue from customer 
group by shipping_type
having shipping_type in ('Express', 'Standard')

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status, avg(purchase_amount) as avg_spend, sum(purchase_amount) as total_revenue from customer
group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, (100 * sum(case when discount_applied = 'Yes' then 1 Else 0 end)/count(*)) as discount_rate from customer 
group by item_purchased
order by discount_rate desc

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
--    and show the count of each segment. 
with customer_type as (
select case
when previous_purchases < 3 then 'new'
when previous_purchases >= 3 and previous_purchases <= 10 then 'returning'
else 'loyal'
end as customer_loyality
from customer
)
select customer_loyality, count(*) as number_of_customers from customer_type
group by customer_loyality 
order by number_of_customers desc

--Q8. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(previous_purchases) repeat_buyers from customer
where previous_purchases > 5
group by subscription_status

--Q9. What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount) as revenue from customer
group by age_group
order by revenue desc
